// Auto-generated by build_price_data_from_deep_dive.py — re-run after Excel changes.
var PRICE_DATA = {
  "products": {
    "TILES": [
      {
        "d": "Floor/Wall Tile | Homeland Range - 300x600 mm",
        "p": 18.1818,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Reef Range - 300x600mm",
        "p": 22.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Fuji Range - 600x600mm",
        "p": 22.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Kempsey Range - 300x600mm",
        "p": 33.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Pietra Rapolano Range - 300x600mm",
        "p": 35.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Limestone Range - 300x600mm",
        "p": 35.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Amalfi Range - 370x750mm",
        "p": 42.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Floor/Wall Tile | Aus Bianco Carrara Range - 300x600mm",
        "p": 42.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Wall Tile |Rectified - White Gloss - 300x600mm",
        "p": 20.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Wall Tile | Rectified - White Gloss or Matt - 300x600mm",
        "p": 20.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Wall Tile | Non-Rectified - White Gloss or Matt - 300x600, 100x300, 75x300",
        "p": 20.0,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Feature Tile | Rectified - Bianco Ripple Gloss - 300x600",
        "p": 36.3636,
        "u": "m2",
        "s": "Rosetto"
      },
      {
        "d": "Subway Tile | Non-Rectified - Ripple - AUS range - 75x300",
        "p": 45.4545,
        "u": "m2",
        "s": "Rosetto"
      }
    ],
    "OVENS": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 600.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range:  Artusi 60cm Electric Built-In Oven",
        "p": 500.0,
        "u": "ea",
        "c": "CAO601B/2",
        "f": "88L capacity, 5 cooking functions, triple-glazed door",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 60cm Electric Oven",
        "p": 600.0,
        "u": "ea",
        "c": "WVE6314SD",
        "f": "80L capacity, 7 functions, stainless steel finish",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1100.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Westinghouse 60cm Multifunction Oven",
        "p": 1000.0,
        "u": "ea",
        "c": "WVE615S",
        "f": "80L capacity, 7 cooking functions, stainless steel finish",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 60cm Series 5 Contemporary Oven",
        "p": 1100.0,
        "u": "ea",
        "c": "OB60SC7CEX3",
        "f": "7 functions, 85L capacity, stainless steel finish",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 60cm Series 5 Pyrolytic Oven",
        "p": 1400.0,
        "u": "ea",
        "c": "OB60SC7CEPX3",
        "f": "85L capacity, 7 functions including Pyrolytic Self-Clean, stainless steel finish",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 2400.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Bosch Series 8 60cm Built-In Pyrolytic Oven",
        "p": 2400.0,
        "u": "ea",
        "c": "HBG7741B1A",
        "f": "Pyrolytic self-cleaning, 71L capacity, black finish",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Fisher & Paykel Series 7 Contemporary Pyrolytic Oven",
        "p": 2600.0,
        "u": "ea",
        "c": "OB60SD13PLX1",
        "f": "13 functions, including Air Fry, Pastry Bake, Pizza Bake, Roast, Slow Cook, and Pyrolytic Self-Cleaning",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 3000.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Electrolux 60cm Multifunction Oven",
        "p": 2800.0,
        "u": "ea",
        "c": "EVEP619DSE",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Electrolux 60cm Pyrolytic Steam Oven",
        "p": 2900.0,
        "u": "ea",
        "c": "EVEP619DSE",
        "f": "Pyrolytic self-cleaning, steam cooking, dark stainless steel finish",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG Series 9 InstaView™ 6-in-1 Oven",
        "p": 3200.0,
        "u": "ea",
        "f": "Combines convection, air fry, steam, sous vide, and more; InstaView™ door for easy viewing; ThinQ® app compatibility.",
        "t": "Prestige"
      }
    ],
    "COOKTOPS": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 600.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 60cm Ceramic Cooktop",
        "p": 500.0,
        "u": "ea",
        "c": "CACC60",
        "f": "4 cooking zones, touch controls, residual heat indicators",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 60cm Gas Cooktop",
        "p": 400.0,
        "u": "ea",
        "c": "CAGH600CIX",
        "f": "4 burners including wok, stainless steel finish, flame failure safety",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 60cm 4 Zone Ceramic Cooktop",
        "p": 550.0,
        "u": "ea",
        "c": "WHC642BC",
        "f": "Touch controls, residual heat indicators, and sleek black ceramic glass surface.",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 60cm 4 Burner Gas Cooktop",
        "p": 600.0,
        "u": "ea",
        "c": "WHG644SC",
        "f": "Stainless steel finish, flame failure safety device, easy-clean surface",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1100.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 60cm Series 5 4 Burner Gas Cooktop",
        "p": 1000.0,
        "u": "ea",
        "c": "CG604CNGX2",
        "f": "4 burners including wok burner, stainless steel finish",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 60cm Series 5 4 Element Electric Cooktop",
        "p": 1000.0,
        "u": "ea",
        "c": "CE604CBX2",
        "f": "4 cooking zones, ceramic glass surface, touch controls",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Electrolux 60cm Induction Cooktop",
        "p": 1200.0,
        "u": "ea",
        "c": "EHI645BF",
        "f": "4 induction zones, touch controls, black ceramic glass surface",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Bosch Series 6 60cm Induction Cooktop",
        "p": 1300.0,
        "u": "ea",
        "c": "PVS631HC1H",
        "f": "Touch controls, 4 induction zones",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 2000.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Bosch Series 8 60cm Gas Cooktop",
        "p": 1800.0,
        "u": "ea",
        "c": "PRP6A6B70A",
        "f": "Ceramic glass surface, 4 burners including wok burner",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 3000.0,
        "u": "ea",
        "t": "Prestige"
      }
    ],
    "RANGEHOODS": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 300.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 60cm Slide-Out Rangehood",
        "p": 250.0,
        "u": "ea",
        "c": "WRR604SB",
        "f": "340m³/hr extraction, 3 fan speeds, LED lighting",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 60cm Slide-Out Rangehood",
        "p": 300.0,
        "u": "ea",
        "c": "ASO600X",
        "f": "529 m³/hr extraction, 3 speed settings, stainless steel finish",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 60cm Canopy Rangehood (Stainless Steel)",
        "p": 300.0,
        "u": "ea",
        "c": "ACH600X",
        "f": "529 m³/hr extraction, 3 speed settings, stainless steel finish",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 600.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Westinghouse 60cm Canopy Rangehood",
        "p": 500.0,
        "u": "ea",
        "c": "WRC614SD",
        "f": "Stainless steel finish, 3 fan speeds, 600m³/hr extraction rate",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 60cm Built-in Telescopic Slideout Rangehood",
        "p": 500.0,
        "u": "ea",
        "c": "HS60LXW4",
        "f": "2 fan speeds, 180m³/hr extraction, LED lighting",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Bosch Series 2 60cm Slide-Out Rangehood",
        "p": 600.0,
        "u": "ea",
        "c": "DFM064W54A",
        "f": "Silver metallic finish, 3-speed fan",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: LG 60cm Slide-Out Rangehood",
        "p": 600.0,
        "u": "ea",
        "f": "Compact design; efficient extraction; LED lighting.",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: LG 60cm Integrated Rangehood",
        "p": 700.0,
        "u": "ea",
        "f": "Seamless integration into cabinetry; powerful extraction; quiet operation.",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 800.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Bosch Series 2 60cm Wall-Mounted Canopy Rangehood",
        "p": 800.0,
        "u": "ea",
        "c": "DWP66BC50A",
        "f": "Stainless steel finish, 3-speed fan",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Electrolux 86cm Integrated Rangehood",
        "p": 900.0,
        "u": "ea",
        "c": "ERI955DSE",
        "f": "830m³/hr airflow, Hob2Hood technology, dark stainless steel finish",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 1200.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG 90cm T-Shape Canopy Rangehood",
        "p": 1000.0,
        "u": "ea",
        "c": "BWH907T3S",
        "f": "Modern T-shape design; ThinQ® app compatibility; high extraction rate.",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Fisher & Paykel 60cm Canopy Rangehood",
        "p": 1400.0,
        "u": "ea",
        "c": "HC60PLX4",
        "f": "3 fan speeds, 780m³/hr extraction, stainless steel finish",
        "t": "Prestige"
      }
    ],
    "DISHWASHERS": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 700.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 60cm Freestanding Dishwasher",
        "p": 700.0,
        "u": "ea",
        "c": "ADW5001X",
        "f": "Stainless steel finish, multiple wash programs",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 60cm Freestanding Dishwasher",
        "p": 700.0,
        "u": "ea",
        "c": "WSF6606XB",
        "f": "15 place settings, 6 wash programs, stainless steel finish",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1000.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Westinghouse 60cm Built-Under Dishwasher",
        "p": 1100.0,
        "u": "ea",
        "c": "WSU6608KXB",
        "f": "14 place settings, 6 wash programs, delay start, and stainless steel finish.",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 1500.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Bosch Series 6 Fully Integrated Dishwasher",
        "p": 1500.0,
        "u": "ea",
        "c": "SMV6HCX01A",
        "f": "15 place settings, Home Connect, stainless steel finish",
        "t": "Premium"
      },
      {
        "d": "Premium Range: LG 14 Place QuadWash® Built-Under Dishwasher",
        "p": 1600.0,
        "u": "ea",
        "c": "XD4B24UPS",
        "f": "QuadWash® technology for thorough cleaning; TrueSteam® for sparkling results; ThinQ® app compatibility.",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 2000.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Fisher & Paykel 60cm Single DishDrawer Dishwasher",
        "p": 1600.0,
        "u": "ea",
        "c": "DD60SCX9",
        "f": "7 place settings, 6 wash programs, stainless steel finish",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Electrolux 15-Place Setting Fully Integrated Dishwasher",
        "p": 1700.0,
        "u": "ea",
        "c": "ESL79200RO",
        "f": "ComfortLift mechanism, AirDry technology, stainless steel finish",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG 15 Place QuadWash® Freestanding Dishwasher",
        "p": 1800.0,
        "u": "ea",
        "c": "XD2A25MB",
        "f": "Matte black finish; TrueSteam® technology; ultra-quiet operation at 40dBA.",
        "t": "Prestige"
      }
    ],
    "FRIDGES": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 1200.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 425L Bottom Mount Fridge",
        "p": 1100.0,
        "u": "ea",
        "c": "WBE4302WCL",
        "f": "FlexStor adjustable shelving, frost-free system, white finish",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1600.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Westinghouse 496L Bottom Mount Refrigerator",
        "p": 1500.0,
        "u": "ea",
        "c": "WBE5300SC-R",
        "f": "FlexStor adjustable door bins, SpillSafe glass shelves, stainless steel finish",
        "t": "Lifestyle"
      },
      {
        "d": "Lfiestyle Range: Fisher & Paykel 442L Bottom Mount Fridge",
        "p": 1100.0,
        "u": "ea",
        "c": "RF442BRPX6",
        "f": "ActiveSmart™ technology, stainless steel finish, adjustable glass shelves"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 2500.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Fisher & Paykel 487L Series 7 French Door Refrigerator",
        "p": 2300.0,
        "u": "ea",
        "c": "RF610ADUX5",
        "f": "ActiveSmart technology, stainless steel finish",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 4000.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Electrolux 609L French Door Refrigerator",
        "p": 3200.0,
        "u": "ea",
        "c": "EHE6899SA",
        "f": "SmartSplit door, fully convertible drawer, TasteLock easy glide crispers",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Bosch Series 6 French Door Bottom Mount Fridge",
        "p": 3500.0,
        "u": "ea",
        "c": "KFN96AXEAA",
        "f": "Brushed black steel finish, Total NoFrost technology",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG 847L French Door Fridge with InstaView™ Door-in-Door®",
        "p": 4900.0,
        "u": "ea",
        "f": "Large capacity; InstaView™ panel; Door-in-Door® design for easy access; ThinQ® app compatibility.",
        "t": "Prestige"
      }
    ],
    "WASHING MACHINES": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 600.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 7.5kg Front Load Washing Machine",
        "p": 550.0,
        "u": "ea",
        "c": "WWF7524N3WA",
        "f": "12 wash programs, 1200rpm spin speed, white finish",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Artusi 8kg Front Load Washing Machine",
        "p": 550.0,
        "u": "ea",
        "c": "AWM1814W",
        "f": "15 wash programs, eco wash function, white enamel finish",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1100.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Westinghouse 9kg EasyCare Front Load Washer Dryer Combo",
        "p": 1100.0,
        "u": "ea",
        "f": "5 wash programs, 1400rpm spin speed, white finish",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 8kg Front Load Washing Machine",
        "p": 1000.0,
        "u": "ea",
        "c": "WH8060J3",
        "f": "SmartDrive technology, 13 wash cycles, white finish",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 1500.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Electrolux 12kg UltimateCare 900 Front Load Washing Machine",
        "p": 1400.0,
        "u": "ea",
        "c": "EWF1242R9WC",
        "f": "UltraMix technology, 15 wash programs, white finish",
        "t": "Premium"
      },
      {
        "d": "Premium Range: Bosch Series 8 9kg Front Load Washing Machine",
        "p": 1300.0,
        "u": "ea",
        "c": "WAW28460AU",
        "f": "EcoSilence Drive, 1400 rpm spin speed, white finish",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 2000.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG 12kg Front Load Washing Machine with AI Direct Drive™",
        "p": 1800.0,
        "u": "ea",
        "f": "AI technology for optimal wash cycles; TurboClean™ 360; ThinQ® app compatibility.",
        "t": "Prestige"
      }
    ],
    "DRYERS": [
      {
        "d": "Essentials Range: General Allowance - selection to be confirmed",
        "p": 500.0,
        "u": "ea",
        "t": "Essentials"
      },
      {
        "d": "Essentials Range: Westinghouse 5.5kg Vented Dryer",
        "p": 400.0,
        "u": "ea",
        "c": "WDV556N3WB",
        "f": "Sensor drying, reverse tumbling, wall-mountable",
        "t": "Essentials"
      },
      {
        "d": "Lifestyle Range: General Allowance - selection to be confirmed",
        "p": 1000.0,
        "u": "ea",
        "t": "Lifestyle"
      },
      {
        "d": "Lifestyle Range: Fisher & Paykel 8kg Condensing Dryer",
        "p": 1200.0,
        "u": "ea",
        "c": "DE8060P2",
        "f": "Auto-sensing technology, stainless steel drum",
        "t": "Lifestyle"
      },
      {
        "d": "Premium Range: General Allowance - selection to be confirmed",
        "p": 1500.0,
        "u": "ea",
        "t": "Premium"
      },
      {
        "d": "Prestige Range: General Allowance - selection to be confirmed",
        "p": 2000.0,
        "u": "ea",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Electrolux 9kg UltimateCare 900 Steam Heat Pump Dryer",
        "p": 1900.0,
        "u": "ea",
        "c": "EDH902R9SC",
        "f": "D Sense technology, steam function, dark onyx finish",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: Bosch Series 8 8kg Heat Pump Dryer",
        "p": 1900.0,
        "u": "ea",
        "c": "WQG235D8AU",
        "f": "ActiveAir Technology, self-cleaning condenser, white finish",
        "t": "Prestige"
      },
      {
        "d": "Prestige Range: LG 9kg Heat Pump Dryer with Dual Inverter Heat Pump™",
        "p": 2000.0,
        "u": "ea",
        "f": "Energy-efficient drying; Allergy Care™ cycle; ThinQ® app compatibility.",
        "t": "Prestige"
      }
    ]
  },
  "trade": {
    "Balustrade": [
      {
        "d": "Supply and install Glass Balustrade — 12mm Glass with Silver Nano Rail",
        "p": 550.0,
        "u": "lm"
      },
      {
        "d": "Supply and install Glass Balustrade — 15mm Glass - Frameless with No Rail",
        "p": 650.0,
        "u": "lm"
      },
      {
        "d": "Supply and install Glass Balustrade — 15mm Glass - Stand off glass system with No Rail",
        "p": 810.0,
        "u": "lm"
      },
      {
        "d": "Supply and install Glass Stair Balustrade — 12mm Glass with Silver Nano Rail",
        "p": 850.0,
        "u": "lm"
      },
      {
        "d": "Supply and install Glass Stair Balustrade — 15mm Glass - Frameless with No Rail",
        "p": 950.0,
        "u": "lm"
      },
      {
        "d": "Supply and install Glass Stair Balustrade — 15mm Glass - Stand off glass system with No Rail",
        "p": 1164.0,
        "u": "lm"
      }
    ],
    "Brickwork": [
      {
        "d": "Lay standard face bricks — Labour rate for bricklyaing",
        "p": 2.0,
        "u": "per brick"
      },
      {
        "d": "Lay 100 & 150 series blocks — Labour rate for blocklaying",
        "p": 6.0,
        "u": "per brick"
      },
      {
        "d": "Lay 200 series blocks — Labour rate for blocklaying",
        "p": 9.0,
        "u": "per brick"
      },
      {
        "d": "Lay 240 series blocks — Labour rate for blocklaying",
        "p": 9.0,
        "u": "per brick"
      },
      {
        "d": "Lay 300 series blocks — Labour rate for blocklaying",
        "p": 12.0,
        "u": "per brick"
      },
      {
        "d": "Cut rate - new home — Single Storey rate applied",
        "p": 600.0,
        "u": "ea"
      },
      {
        "d": "Cut rate - small ext/reno — Single Storey rate applied",
        "p": 300.0,
        "u": "ea"
      },
      {
        "d": "Cut rate - large ext /reno — Single Storey rate applied",
        "p": 600.0,
        "u": "ea"
      },
      {
        "d": "Cut rate - new home — Double Storey rate applied",
        "p": 1300.0,
        "u": "ea"
      },
      {
        "d": "Cut rate - small ext/reno — Double Storey rate applied",
        "p": 450.0,
        "u": "ea"
      },
      {
        "d": "Cut rate - blocks - base cuts — Cut rate for blockwork",
        "p": 500.0,
        "u": "ea"
      },
      {
        "d": "Carting rate - brick elevator — Rate includes hire and labour",
        "p": 800.0,
        "u": "ea"
      },
      {
        "d": "Carting rate - manual — Labour rate for carting bricks around site applied",
        "p": 800.0,
        "u": "ea"
      },
      {
        "d": "Construct Brick Piers — Face Bricks - Labour rate for bricklyaing",
        "p": 500.0,
        "u": "ea"
      },
      {
        "d": "Construct Brick Piers — Sub Floor Bricks - Labour rate for bricklaying",
        "p": 80.0,
        "u": "ea"
      },
      {
        "d": "Lay sill bricks — Labour rate for bricklyaing",
        "p": 45.0,
        "u": "lm"
      },
      {
        "d": "Hourly rate - bricky — General labour allowance",
        "p": 80.0,
        "u": "hr"
      },
      {
        "d": "Hourly rate - labourer — General labour allowance",
        "p": 50.0,
        "u": "hr"
      },
      {
        "d": "Generator hire — Daily rate applied",
        "p": 60.0,
        "u": "day"
      },
      {
        "d": "Lay open fire & chimney — Single Storey rate applied",
        "p": 10000.0,
        "u": "ea"
      },
      {
        "d": "Lay open fire & chimney — Double Storey rate applied",
        "p": 14000.0,
        "u": "ea"
      }
    ],
    "Plastering": [
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 38.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 40.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 42.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — Raked Ceiling - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 40.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — Raked Ceiling - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 42.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — Raked Ceiling - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 44.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 44.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 46.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 48.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm Fyrcheck - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 47.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm Fyrcheck - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 49.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 13mm Fyrcheck - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 51.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 16mm Fyrcheck - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 52.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 16mm Fyrcheck - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 54.0,
        "u": "m2"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - new work — 16mm Fyrcheck - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 56.0,
        "u": "m2"
      },
      {
        "d": "Plastering - Other Services — Square set plaster finishing - large window and/or door",
        "p": 420.0,
        "u": "ea"
      },
      {
        "d": "Plastering - Other Services — Square set plaster finishing - standard window and/or door",
        "p": 320.0,
        "u": "ea"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 9m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3075.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 9m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3280.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 9m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3587.5,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 12m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3280.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 12m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3485.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 12m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3895.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 16m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3485.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 16m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3690.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 16m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3895.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 25m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3690.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 25m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3895.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 25m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 4305.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 36m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3895.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 36m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 4100.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - renovation work — 36m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 4510.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 6m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 2870.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 6m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3075.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 6m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3382.5,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 9m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3075.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 9m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3280.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 9m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3587.5,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 12m2 room - 10mm - 2.4m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3280.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 12m2 room - 10mm - 2.7m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3485.0,
        "u": "room"
      },
      {
        "d": "Supply, install and prepare plaster sheeting - bathroom — 12m2 room - 10mm - 3.0m ceiling - R5.0 ceiling - R2.5 ext walls",
        "p": 3895.0,
        "u": "room"
      },
      {
        "d": "Plastering - Other Services — Square set plaster finishing - large window and/or door",
        "p": 420.0,
        "u": "ea"
      },
      {
        "d": "Plastering - Other Services — Square set plaster finishing - standard window and/or door",
        "p": 320.0,
        "u": "ea"
      },
      {
        "d": "Plastering - Other Services — Supply and install standard cove cornice - 2.4m ceiling",
        "p": 20.0,
        "u": "lm"
      },
      {
        "d": "Plastering - Other Services — Supply and install standard cove cornice - 2.4m ceiling",
        "p": 22.0,
        "u": "lm"
      },
      {
        "d": "Plastering - Other Services — Supply and install standard cove cornice - 2.4m ceiling",
        "p": 24.0,
        "u": "lm"
      },
      {
        "d": "Plastering - Other Services — Plaster patching - minimum rate work",
        "p": 420.0,
        "u": "ea"
      },
      {
        "d": "Plastering - Other Services — Plaster patching - all types",
        "p": 95.0,
        "u": "m2"
      },
      {
        "d": "Plastering - Other Services — Plaster patching - GPO & switch holes",
        "p": 210.0,
        "u": "ea"
      },
      {
        "d": "Plastering - Other Services — Plaster Patching - hourly rate",
        "p": 90.0,
        "u": "hr"
      }
    ],
    "Electrical": [
      {
        "d": "Supply and install GPO — Double GPO - Clipsal Iconic or equivalent",
        "p": 77.22,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Single GPO - Clipsal Iconic or equivalent",
        "p": 79.25,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Dishwasher - Clipsal Iconic or equivalent",
        "p": 79.25,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Roller Door - Clipsal Iconic or equivalent",
        "p": 79.25,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — USB/Double GPO - Clipsal Iconic or equivalent",
        "p": 168.33,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Outdoor Double GPO - Clipsal Iconic or equivalent",
        "p": 103.59,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED Downlight - Clipsal Iconic or equivalent - White",
        "p": 88.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED Batten - 4ft light or equivalent",
        "p": 125.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — Batten Holder - Inc: globe and timber support",
        "p": 77.69,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — External Wall Light -",
        "p": 160.87,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — Internal Wall Light -",
        "p": 160.87,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED strip lighting up to 5m with extrusion",
        "p": 302.4,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Install Lights only — Install light fitting supplied by owner or builder",
        "p": 94.17,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install dimmer — Clipsal Iconic or equivalent",
        "p": 128.69,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install movement sensor — Clipsal Iconic or equivalent - 63mm and 360deg",
        "p": 167.62,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 1 gang light switch -Clipsal Iconic or equivalent",
        "p": 63.44,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 2 gang light switch -Clipsal Iconic or equivalent",
        "p": 79.63,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 3 gang light switch -Clipsal Iconic or equivalent",
        "p": 99.7,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 4 gang light switch -Clipsal Iconic or equivalent",
        "p": 113.94,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 5 gang light switch -Clipsal Iconic or equivalent",
        "p": 129.41,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 6 gang light switch -Clipsal Iconic or equivalent",
        "p": 145.96,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 2 way light switch -Clipsal Iconic or equivalent",
        "p": 35.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 3 way light switch -Clipsal Iconic or equivalent",
        "p": 95.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install smoke detector — Photoelectric and interconnected",
        "p": 111.83,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install hot water connection — Includes isolation switch",
        "p": 164.44,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install oven circuit and connection — Allowance for Clipsal Iconic or equivalent",
        "p": 294.3,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install rangehood power and ducting — NOTE: does not include installation of rangehood",
        "p": 112.86,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install extraction fan — Ventair Sahara unit inc: cable and ducting to outside air",
        "p": 625.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install extraction fan — Airbus 300 - inc: cable and ducting to outside air",
        "p": 378.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light/heater/fan combo — Allowance for ??? Inc: cable and ducting to outside air",
        "p": 460.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install TV wiring — Inc: 1 TV point (Clipsal Iconic), Antenna and splitter",
        "p": 400.24,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install TV wiring — Additional TV points",
        "p": 70.2,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Data point — CAT6 - Clipsal Iconic or equivalent",
        "p": 129.49,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install NBN conduit — Allowance for wiring from external pit to inside location",
        "p": 350.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Install sweep fan — Allowance to install fan supplied by owner or builder",
        "p": 168.95,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install power for AWTS — Allowance for up to 25m from dwelling",
        "p": 299.75,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install power for external pump — Allowance for up to 20m from dwelling",
        "p": 250.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install floor box — Allowance for Clipsal Iconic or equivalent",
        "p": 500.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Decommission fee — Disconnect and make safe for demolition work - large renovation",
        "p": 900.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Decommission fee — Disconnect and make safe for demolition work - small renovation",
        "p": 600.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Decommission fee — Disconnect and make safe for demolition work - single room",
        "p": 300.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Double GPO - Clipsal Iconic or equivalent",
        "p": 84.942,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Single GPO - Clipsal Iconic or equivalent",
        "p": 87.175,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Dishwasher - Clipsal Iconic or equivalent",
        "p": 87.175,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Dishwasher - Clipsal Iconic or equivalent",
        "p": 87.175,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — USB/Double GPO - Clipsal Iconic or equivalent",
        "p": 185.163,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install GPO — Outdoor Double GPO - Clipsal Iconic or equivalent",
        "p": 113.949,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED Downlight - Clipsal Iconic or equivalent - White",
        "p": 96.8,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED Batten - 4ft light or equivalent",
        "p": 137.5,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — Batten Holder - Inc: globe and timber support",
        "p": 85.459,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — External Wall Light -",
        "p": 176.957,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — Internal Wall Light -",
        "p": 176.957,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Lights — LED strip lighting up to 5m with extrusion",
        "p": 332.64,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Install Lights — Install light fitting supplied by owner or builder",
        "p": 103.587,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install dimmer — Clipsal Iconic or equivalent",
        "p": 141.559,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install movement sensor — Clipsal Iconic or equivalent - 63mm and 360deg",
        "p": 184.382,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 1 gang light switch -Clipsal Iconic or equivalent",
        "p": 69.784,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 2 gang light switch -Clipsal Iconic or equivalent",
        "p": 87.593,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 3 gang light switch -Clipsal Iconic or equivalent",
        "p": 109.67,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 4 gang light switch -Clipsal Iconic or equivalent",
        "p": 125.334,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 5 gang light switch -Clipsal Iconic or equivalent",
        "p": 142.351,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 6 gang light switch -Clipsal Iconic or equivalent",
        "p": 160.556,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 2 way light switch -Clipsal Iconic or equivalent",
        "p": 38.5,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light switch — 3 way light switch -Clipsal Iconic or equivalent",
        "p": 104.5,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install smoke detector — Photoelectric and interconnected",
        "p": 123.013,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install hot water connection — Includes isolation switch",
        "p": 180.884,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install oven circuit and connection — Allowance for Clipsal Iconic or equivalent",
        "p": 323.73,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install rangehood power and ducting — NOTE: does not include installation of rangehood",
        "p": 124.146,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install extraction fan — Ventair Sahara unit inc: cable and ducting to outside air",
        "p": 687.5,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install extraction fan — Airbus 300 - inc: cable and ducting to outside air",
        "p": 415.8,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install light/heater/fan combo — Allowance for ??? Inc: cable and ducting to outside air",
        "p": 506.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install TV wiring — Inc: 1 TV point (Clipsal Iconic), Antenna and splitter",
        "p": 440.264,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install TV wiring — Additional TV points",
        "p": 77.22,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Data point — CAT6 - Clipsal Iconic or equivalent",
        "p": 142.439,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install NBN conduit — Allowance for wiring from external pit to inside location",
        "p": 385.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Install sweep fan — Allowance to install fan supplied by owner or builder",
        "p": 185.845,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install power for AWTS — Allowance for up to 25m from dwelling",
        "p": 329.725,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install power for external pump — Allowance for up to 20m from dwelling",
        "p": 275.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install floor box — Allowance for Clipsal Iconic or equivalent",
        "p": 550.0,
        "u": "ea",
        "s": "SKE"
      }
    ],
    "Electrical Mains": [
      {
        "d": "Supply & install slab earth bond",
        "p": 15.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply & install 32amp circuit",
        "p": 250.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply & install switchboard — inc - single phase, meter panel + RCBOS and strip earth",
        "p": 1650.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply & install mains — inc - 25mm single phase per meter inc conduit - min 20m",
        "p": 906.4,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply & install mains — per metre cost over 20m",
        "p": 45.32,
        "u": "lm",
        "s": "SKE"
      }
    ],
    "Heating": [
      {
        "d": "Supply and install Air Conditioning — 7kw - Split system - Wall mounted",
        "p": 3000.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Air Conditioning — 7kw - Split system - Floor mounted",
        "p": 5000.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Air Conditioning — 12kw - Ducted System - 8 vents",
        "p": 10000.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Air Conditioning — 16.5kw - Ducted System - 10 vents",
        "p": 11250.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Air Conditioning — 18kw  - Ducted system - 12 vents",
        "p": 240.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Ducted zoning — 6 zones",
        "p": 3000.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Ducted zoning — 8 zones",
        "p": 3350.0,
        "u": "ea",
        "s": "SKE"
      },
      {
        "d": "Supply and install Ducted zoning — 10 zones",
        "p": 3800.0,
        "u": "ea",
        "s": "SKE"
      }
    ],
    "Plumbing": [
      {
        "d": "Standard plumbing installation for hot and cold - new dwelling — Kitchen/dishwasher/laundry/wahsing machies/bathroom/garden taps/HWC connection inc slab/downpipes/vent",
        "p": 5200.0,
        "u": "ea",
        "s": "vince"
      },
      {
        "d": "Standard plumbing installation for hot and cold - ensuite — Toilet basin and shower",
        "p": 1370.0,
        "u": "ea",
        "s": "vince"
      },
      {
        "d": "Supply and install Sewer drainage — Sewer - 100mm - Inc: excavation and/or backfill",
        "p": 45.0,
        "u": "lm",
        "s": "Vince"
      },
      {
        "d": "Supply and install Sewer drainage — Sewer - Suspended - 100mm",
        "p": 60.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Sewer drainage — Swivel Joints - Requirement for class H1 soil and above",
        "p": 210.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Sewer drainage — Sewer Vent - Single storey",
        "p": 305.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Sewer drainage — ORG for sewer - Requirement for new build",
        "p": 160.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater - Suspended - 100mm",
        "p": 40.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater - 100mm - Inc: excavation and/or backfill",
        "p": 60.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater - 150mm - Inc: excavation and/or backfill",
        "p": 80.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Agg Drain - 100mm - inc: excavation, pipe, fabric and 20mm gravel backfill",
        "p": 60.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Swivel Joints - Requirement for class H1 soil and above",
        "p": 210.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater Pit - 350x350mm",
        "p": 325.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater Pit - 450x450mm",
        "p": 475.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — Stormwater Pit - 600x6000mm",
        "p": 650.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — External Grated Draing - 100mm trench drain and end caps",
        "p": 200.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Stormwater drainage — External Grated Drain - 150mm trench drain and end caps",
        "p": 310.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Detention tank connection — Above ground installation only",
        "p": 500.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Undertake core drilling — Eg: slab/footing/brick - Inc: hire of equipment and labour",
        "p": 250.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Mains water pipe — Poly Mains water pipe - 25mm",
        "p": 35.0,
        "u": "lm",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install Mains water pipe — Pressure Limiting Valve - Requirement for every new build",
        "p": 210.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Toilet suite and stop tap",
        "p": 220.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Install in wall cistern for toilet suite",
        "p": 250.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Hand basin and tapware",
        "p": 230.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Sink and tapware",
        "p": 250.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Shower head and tapware",
        "p": 300.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Bath and tapware - standard fit off",
        "p": 500.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Bath and tapware - slab or inaccessible space",
        "p": 600.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Spa bath and tapware - standard fit off",
        "p": 550.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Plumbing and Sanitary item — Spa bath and tapware - slab or inaccessible space",
        "p": 650.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install internal stop tap — Fridge - Does not include installation of fridge",
        "p": 180.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install internal stop tap — Dishwasher - includes installation of dishwasher",
        "p": 250.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install internal stop tap — Washing Machine - excludes installation of machine",
        "p": 180.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Supply and install garden tap — Brass garden tap inc: vacuum breaker",
        "p": 175.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Gas Connection — Inc: 160Mj/h regulator, pipework up to 10m, compliance, commission, chains, 1 x gas point",
        "p": 1150.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Gas Appliance — Cooktop",
        "p": 300.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Gas Appliance — Hot Water",
        "p": 300.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Install Gas Appliance — Bayonet Fitting (eg: for BBQ or heater)",
        "p": 800.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Room Renovation — Bathroom - Inc: all plumbing rqd down to floor level",
        "p": 4000.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Room Renovation — Ensuite - Inc: all plumbing rqd down to floor level",
        "p": 3400.0,
        "u": "ea",
        "s": "Pinnacle"
      },
      {
        "d": "Room Renovation — Powder Room - Inc: all plumbing rqd down to floor level",
        "p": 2500.0,
        "u": "ea",
        "s": "Pinnacle"
      }
    ],
    "Roofing": [
      {
        "d": "Supply & install new roof, fascia & gutter — 2-23 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 80.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — 24-30 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 85.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — 31-45 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 95.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — less than 2 deg or complex roof",
        "p": 120.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install parpet flashings — as marked on plans",
        "p": 75.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install metal rainheads — as marked on plans",
        "p": 500.0,
        "u": "ea",
        "s": "Sutton"
      },
      {
        "d": "Supply & install metal box gutters — as marked on plans",
        "p": 80.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install ventilation battens",
        "p": 12.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install metal gutter & valley guard — as marked on plans",
        "p": 40.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install safety guard rails — For duration of roofing work only",
        "p": 21.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Roofing Services — Hourly rate work",
        "p": 120.0,
        "u": "hr",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — 5-23 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 100.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — 24-30 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 105.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — 31-45 deg pitch - Corrugated or Trimdek, Quad Gutter",
        "p": 120.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new roof, fascia & gutter — less than 5 deg or complex roof",
        "p": 135.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Remove & dispose of roof tiles — as marked on plans",
        "p": 100.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Remove & dispose of old roofing — as marked on plans",
        "p": 15.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install ventilation battens",
        "p": 12.0,
        "u": "m2",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new metal fascia",
        "p": 33.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new metal gutter — Quad gutter or \"to match\"",
        "p": 33.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new metal cap fascia — as required",
        "p": 50.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install new metal barge flashings — as required",
        "p": 50.0,
        "u": "lm",
        "s": "Sutton"
      },
      {
        "d": "Supply & install skylight — Single storey - including flashings",
        "p": 1400.0,
        "u": "ea",
        "s": "Sutton"
      },
      {
        "d": "Supply & install skylight — Double storey - including flashings",
        "p": 1900.0,
        "u": "ea",
        "s": "Sutton"
      },
      {
        "d": "Supply skylight flashings",
        "p": 200.0,
        "u": "ea",
        "s": "Sutton"
      }
    ]
  }
};
